import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./commbonades/header";
import Popover from "./commbonades/Popover";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={inter.className}>
        <Header />
        <Popover />
        {children}
      </body>
    </html>
  );
}
