import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/app/[locale]/(components)/header';
import Popover from './(components)/Popover';
import { useTranslations } from 'next-intl';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}
export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  const t = useTranslations('Navigation');

  return (
    <html lang={locale} dir='rtl'>
      <body className={inter.className} >
        <Header signIn={t('signIn')} xx="wwwwwwww" />
        <Popover/>
        {children}
      </body>
    </html>
  );
}